server:
  port: 18080
#  context-path: /girl
  tomcat:
    uri-encoding: utf-8
girl:
  cupSize: G
  age: 15

spring:
  thymeleaf:
     # 开发过程建议关闭缓存
    cache: false
  freemarker:
    allow-request-override: false
    cache: false
    check-template-location: true
    charset: UTF-8
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false

#content: "cupSize:${cupSize}, age:${age}"