spring:
  profiles:
    active: prod
  datasource:
      password: 111111
      username: root
      url: jdbc:mysql://localhost:3306/dbgirl?useUnicode=true&&characterEncoding=utf8
      driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect

